package com.pigletO.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * DemoServiceService service = new DemoServiceService();
 * DemoService portType = service.getDemoServicePort();
 * portType.serviceOne(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "DemoServiceService", targetNamespace = "http://server.pigletO.com/", wsdlLocation = "http://localhost:8888/service/demoService?wsdl")
public class DemoServiceService extends Service {

	private final static URL DEMOSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.pigletO.client.DemoServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.pigletO.client.DemoServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8888/service/demoService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8888/service/demoService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		DEMOSERVICESERVICE_WSDL_LOCATION = url;
	}

	public DemoServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public DemoServiceService() {
		super(DEMOSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://server.pigletO.com/", "DemoServiceService"));
	}

	/**
	 * 
	 * @return returns DemoService
	 */
	@WebEndpoint(name = "DemoServicePort")
	public DemoService getDemoServicePort() {
		return super.getPort(new QName("http://server.pigletO.com/",
				"DemoServicePort"), DemoService.class);
	}

}
