package com.pigletO.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "DemoService", targetNamespace = "http://server.pigletO.com/")
public interface DemoService {

	/**
     * 
     */
	@WebMethod
	@RequestWrapper(localName = "serviceOne", targetNamespace = "http://server.pigletO.com/", className = "com.pigletO.client.ServiceOne")
	@ResponseWrapper(localName = "serviceOneResponse", targetNamespace = "http://server.pigletO.com/", className = "com.pigletO.client.ServiceOneResponse")
	public void serviceOne();

}
